name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-linux:
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: "21"
    steps:
    - uses: actions/checkout@v4
    - uses: jiro4989/setup-nim-action@v2
      with:
        nim-version: 'stable'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install dependencies
      run: |
        sudo apt install -y openjdk-${{ env.JAVA_VERSION }}-jdk wget unzip
        JAVA_HOME=/usr/lib/jvm/java-${{ env.JAVA_VERSION }}-openjdk-amd64
        echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV
        echo "${JAVA_HOME}/bin" >> $GITHUB_PATH
    - name: Set up Android SDK/NDK
      run: |
        nimble -d:GitHubCI setupBuildEnv -Y
    - name: Run tests
      run: |
        nimble -d:GitHubCI testCI
    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: raylib-game-apk
        path: ${{ github.workspace }}/raylib_game.apk
        if-no-files-found: error
    - name: Install Butler
      run: |
        curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
        unzip butler.zip
        chmod +x butler
        sudo mv butler /usr/local/bin
    - name: Login to Butler
      run: butler login
      env:
        BUTLER_API_KEY: ${{ secrets.BUTLER }}
    - name: Push Android build to Itch.io
      run: butler push ${{ github.workspace }}/raylib_game.apk ${{ secrets.ITCH_URL }}:android
      env:
        BUTLER_API_KEY: ${{ secrets.BUTLER }}