name: Build and Upload Raylib WebAssembly Game

on:
  pull_request:
    branches: [main]
  push:
    branches:
      - main

jobs:
  build:
    environment: web
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: jiro4989/setup-nim-action@v2
      with:
        nim-version: 'stable'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake ninja-build git python3 wget unzip
        sudo apt-get install -y libwayland-dev wayland-protocols libxkbcommon-dev libx11-dev libegl1-mesa-dev
        sudo test -f /usr/share/doc/kitware-archive-keyring/copyright ||
        sudo wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /usr/share/keyrings/kitware-archive-keyring.gpg >/dev/null
        echo 'deb [signed-by=/usr/share/keyrings/kitware-archive-keyring.gpg] https://apt.kitware.com/ubuntu/ focal main' | sudo tee /etc/apt/sources.list.d/kitware.list >/dev/null
        sudo apt-get update
        sudo apt-get install -y kitware-archive-keyring
        sudo apt-get install -y cmake
    - name: Install Emscripten
      run: |
        git clone https://github.com/emscripten-core/emsdk.git
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest
        echo "EMSDK=$PWD" >> $GITHUB_ENV
        echo "EMSCRIPTEN=$PWD/upstream/emscripten" >> $GITHUB_ENV
        echo "$PWD/upstream/emscripten" >> $GITHUB_PATH
    - name: Build Raylib WebAssembly Game
      run: |
        . $EMSDK/emsdk_env.sh
        emcc --version
        nimble -d:emscripten build
    - name: Package Web Build into Zip
      run: |
        cd build/
        zip raylib_web_game.zip *.html *.wasm *.js *.data
    - name: Upload HTML5 Build
      uses: actions/upload-artifact@v3
      with:
        name: html5-build
        path: build/raylib_web_game.zip
    - name: Install Butler
      run: |
        curl -L -o butler.zip https://broth.itch.ovh/butler/linux-amd64/LATEST/archive/default
        unzip butler.zip
        chmod +x butler
        sudo mv butler /usr/local/bin
    - name: Login to Butler
      run: butler login
      env:
        BUTLER_API_KEY: ${{ secrets.BUTLER }}
    - name: Push HTML5 build to Itch.io
      run: butler push build/raylib_web_game.zip ${{ secrets.ITCH_URL }}:html5
      env:
        BUTLER_API_KEY: ${{ secrets.BUTLER }}